// data.jsx — article and editorial content for The Nigerian Economists
// All copy is plausible Nigerian economic commentary; nothing here is real reporting.

const AUTHORS = {
  iyamah: {
    name: "Adesuwa Iyamah",
    initials: "AI",
    role: "Senior Economist",
    affiliation: "Independent; previously CBN Monetary Policy Department, 2014–2021",
    bio: "Adesuwa writes on monetary policy, FX markets, and the political economy of central banking. Her 2023 paper on Naira convertibility is widely cited in policy circles.",
    coi: [
      "Holds no equity in any Nigerian bank or BDC operator.",
      "Consulted for the Lagos State Ministry of Economic Planning, Jan–Apr 2025.",
      "Spouse is employed by a Tier-2 commercial bank; recuses from coverage of that institution.",
    ],
  },
  okoro: {
    name: "Chuka Okoro",
    initials: "CO",
    role: "Contributing Editor, Fiscal Policy",
    affiliation: "Centre for the Study of the Economies of Africa (CSEA)",
    bio: "Chuka covers fiscal policy, subsidy reform, and subnational debt. He served on the Presidential Fiscal Reform Committee in 2023.",
    coi: [
      "Member, Presidential Fiscal Reform Committee, 2023 (unpaid).",
      "No consulting engagements with state governments in the past 24 months.",
    ],
  },
  bello: {
    name: "Fatima Bello",
    initials: "FB",
    role: "Contributor",
    affiliation: "PhD candidate, LSE; formerly NBS",
    bio: "Fatima's research concerns household consumption, inflation measurement, and labour markets in northern Nigeria.",
    coi: ["Funded by a Mastercard Foundation graduate fellowship.", "No paid policy work in the past 12 months."],
  },
  aluko: {
    name: "Tunde Aluko",
    initials: "TA",
    role: "Columnist, Markets",
    affiliation: "Independent",
    bio: "Tunde has covered Nigerian capital markets for two decades, most recently as a buy-side analyst.",
    coi: ["Personal portfolio holdings disclosed quarterly; current disclosure dated 03 May 2026."],
  },
};

const TOPICS = {
  fx:          { slug: "fx",          name: "FX & Monetary Policy",   count: 47 },
  fiscal:      { slug: "fiscal",      name: "Fiscal Policy",          count: 38 },
  subnation:   { slug: "subnation",   name: "Subnational",            count: 18 },
  subsidy:     { slug: "subsidy",     name: "Subsidy & Energy",       count: 22 },
  banking:     { slug: "banking",     name: "Banking & Finance",      count: 31 },
  labour:      { slug: "labour",      name: "Labour & Inflation",     count: 19 },
  welfare:     { slug: "welfare",     name: "Welfare Economics",      count: 24 },
  health:      { slug: "health",      name: "Health Economics",       count: 12 },
  behavioural: { slug: "behavioural", name: "Behavioural Economics",  count: 31 },
  trade:       { slug: "trade",       name: "Trade & AfCFTA",         count: 14 },
  political:   { slug: "political",   name: "Political Economy",      count: 26 },
};

// Main article — full text with inline citation anchors as {{N}} tokens.
// References are resolved by index against the `refs` array.
const ARTICLE_FX_PHANTOM = {
  slug: "phantom-liquidity-fx-window",
  topic: "fx",
  kicker: "Monetary policy",
  headline: "The Phantom Liquidity in Nigeria's FX Window",
  deck: "The CBN's published turnover figures suggest a market that is thickening. The order book tells a different story — and the gap between them is where policy mistakes are made.",
  author: "iyamah",
  publishedISO: "2026-05-08",
  publishedDisplay: "08 May 2026",
  readMinutes: 14,
  wordCount: 3120,
  rebuttedBy: [
    { slug: "phantom-liquidity-response-okeke", author: "Dr. Ngozi Okeke", title: "Reading the NAFEM Tape Correctly", date: "11 May 2026" },
    { slug: "phantom-liquidity-cbn-note",      author: "CBN Research Dept.", title: "A Note on Aggregated Turnover Disclosures", date: "10 May 2026" },
  ],
  paragraphs: [
    { kind: "dropcap", text: "Since the November 2024 reforms to the Nigerian Autonomous Foreign Exchange Market{{1}}, official turnover at the NAFEM window has roughly doubled. The CBN's weekly disclosures, taken at face value, would have us believe that the window is now a functioning interbank market — that the wholesale FX problem is, if not solved, at least manageable. This is the line repeated by the Governor in his last three monetary policy statements{{2}}." },
    { kind: "p", text: "It is not what the order book says." },
    { kind: "p", text: "Between January and April 2026, I obtained anonymised intraday order data from four authorised dealing banks{{3}}, covering 86% of disclosed NAFEM turnover by volume. The data show three features that any practitioner will recognise as symptoms of a thin market dressed up as a thick one." },
    { kind: "h2",  text: "1. The 09:45 spike" },
    { kind: "p", text: "On 71 of 84 trading days in the sample, more than 60% of daily NAFEM turnover cleared in a 15-minute window between 09:30 and 09:45{{4}}. This is not how interbank markets behave. In Johannesburg, Nairobi, or any deep market you would like to name, turnover distributes across the day in something approximating a U-shape. A clearing burst at the open is the signature of a fixing — of trades pre-matched off-book and reported into the window for price discovery purposes." },
    { kind: "rebutted", text: "The Governor has argued that the morning spike reflects 'efficient liquidity provision by market-making banks'{{5}}. The order data do not support this reading. On 62 days, the same two dealers were on both sides of more than 40% of the morning's clearing volume — a pattern more consistent with intra-group settlement than with market-making." },
    { kind: "p", text: "The second feature compounds this. Settlement is concentrated not just in time but in counterparty." },
    { kind: "h2",  text: "2. The disclosed turnover is gross, not net" },
    { kind: "p", text: "NAFEM disclosures aggregate every reported trade, but make no adjustment for reversals or for the now-routine practice of round-tripping a position through an offshore subsidiary to satisfy onshore reporting{{6}}. On the days I examined, an estimated 18–24% of disclosed turnover was reversed within the same session. The CBN is aware of this; the Research Department's own internal memo of February 2026, which I have seen, acknowledges 'material double-counting' in the published series{{7}}." },
    { kind: "pullquote", text: "A clearing burst at the open is the signature of a fixing — not a market." },
    { kind: "p", text: "Adjusting for this, effective NAFEM turnover in Q1 2026 was roughly ₦480bn weekly, against published figures of ₦620bn{{8}}. That is still an improvement over the 2023 baseline. It is not the breakthrough the published numbers imply." },
    { kind: "h2",  text: "3. The rate is pegged, just quietly" },
    { kind: "p", text: "The official NAFEM rate has moved within a 2.1% band over the four-month sample, despite parallel-market pressure of 11–14% over the same period{{9}}. A market in which the rate moves within such a tight band, while a substantial premium persists in an adjacent market, is a market that is being managed. There is nothing inherently wrong with managed convertibility — many emerging economies operate one, and arguably should{{10}}. But it should be called what it is." },
    { kind: "rebutted", text: "Calling NAFEM a 'willing buyer, willing seller' market when its clearing rate moves less than the inflation differential implies is a definitional sleight-of-hand. Policy credibility, which the CBN says it wishes to rebuild{{11}}, is not served by it." },
    { kind: "h2",  text: "What this means for the June MPC" },
    { kind: "p", text: "If the FX window is thinner than disclosed turnover suggests, the case for further tightening at the June MPC is stronger than the Committee's current minutes imply{{12}}. The premium does not close itself. The Committee's options narrow as 2026 progresses." },
    { kind: "p", text: "The honest move would be a methodological revision of the NAFEM disclosure, accompanied by a quiet acknowledgement that the band is wider than published. The dishonest move — and the one I expect — is another quarter of strong turnover figures and a hold." },
  ],
  refs: [
    { author: "CBN", year: 2024, title: "Operational Guidelines for the Nigerian Autonomous Foreign Exchange Market", pub: "CBN Circular FMD/DIR/PUB/CIR/01/021", url: "cbn.gov.ng/fmd-021" },
    { author: "CBN", year: 2026, title: "Monetary Policy Committee Communiqué No. 304", pub: "CBN, March 2026", url: "cbn.gov.ng/mpc-304" },
    { author: "Author's analysis", year: 2026, title: "Anonymised intraday quote-and-deal data, four authorised dealers, Jan–Apr 2026", pub: "On file with the author; data sharing agreement restricts redistribution." },
    { author: "Iyamah, A.", year: 2026, title: "Time-of-day distribution of NAFEM clearing volume, Q1 2026", pub: "Working paper, draft on file." },
    { author: "Cardoso, O.", year: 2026, title: "Address to the Chartered Institute of Bankers of Nigeria, 14 April 2026", pub: "CIBN Lagos, 2026" },
    { author: "Adeyemi, T. & Sani, R.", year: 2025, title: "Round-tripping in the post-2024 NAFEM regime", pub: "CSEA Working Paper 25-11" },
    { author: "CBN Research Dept.", year: 2026, title: "Internal memo on aggregation methodology, NAFEM disclosures", pub: "February 2026, restricted circulation; cited with permission." },
    { author: "Author's calculation", year: 2026, title: "Reversal-adjusted NAFEM turnover series, Q1 2026" },
    { author: "FMDQ Exchange", year: 2026, title: "Parallel market reference rate, weekly close", pub: "FMDQ, Jan–Apr 2026" },
    { author: "Rey, H.", year: 2015, title: "Dilemma not Trilemma: the Global Financial Cycle and Monetary Policy Independence", pub: "NBER Working Paper 21162" },
    { author: "CBN", year: 2025, title: "Monetary Policy Framework Review, 2025", pub: "CBN, November 2025" },
    { author: "CBN MPC", year: 2026, title: "Minutes of the May 2026 Monetary Policy Committee meeting", pub: "CBN, published 02 May 2026" },
  ],
};

const ARTICLES = [
  ARTICLE_FX_PHANTOM,
  {
    slug: "subsidy-three-years-on",
    topic: "subsidy",
    kicker: "Subsidy & Energy",
    headline: "Three Years After Removal, The Subsidy Is Back. We Just Stopped Calling It That.",
    deck: "Implicit subsidisation through the NNPCL's pricing committee has reached an estimated ₦1.8tn annualised. The fiscal arithmetic the 2023 reform was meant to fix has reasserted itself.",
    author: "okoro",
    publishedISO: "2026-05-06",
    publishedDisplay: "06 May 2026",
    readMinutes: 11,
    rebuttedBy: [{ slug: "x", author: "NNPCL Office of the GCEO", title: "On Cost-Recovery Pricing", date: "07 May 2026" }],
  },
  {
    slug: "northern-inflation-divergence",
    topic: "labour",
    kicker: "Inflation",
    headline: "The Northern Inflation Divergence Is Not a Measurement Artefact",
    deck: "Food inflation in Kano and Borno has held 4–6 points above the headline number for eleven consecutive months. The NBS basket is not the problem.",
    author: "bello",
    publishedISO: "2026-05-04",
    publishedDisplay: "04 May 2026",
    readMinutes: 9,
    rebuttedBy: [],
  },
  {
    slug: "primary-health-capitation-failure",
    topic: "health",
    kicker: "Health economics",
    headline: "The Quiet Collapse of Primary-Health Capitation in Eight Northern States",
    deck: "The 2024 NHIA reforms were meant to fix purchasing. Two years on, primary health centres in Kano, Sokoto and Zamfara are receiving capitation transfers a quarter late and at 60 per cent of formula.",
    author: "bello",
    publishedISO: "2026-05-01",
    publishedDisplay: "01 May 2026",
    readMinutes: 9,
    rebuttedBy: [],
  },
  {
    slug: "afcfta-customs-quiet-failure",
    topic: "trade",
    kicker: "Trade",
    headline: "AfCFTA's Quiet Failure at the Customs Counter",
    deck: "Tariff schedules are not the binding constraint. The forms are.",
    author: "okoro",
    publishedISO: "2026-04-29",
    publishedDisplay: "29 Apr 2026",
    readMinutes: 8,
    rebuttedBy: [],
  },
  {
    slug: "tier-2-banks-recapitalisation",
    topic: "banking",
    kicker: "Banking",
    headline: "The Tier-2 Banks Will Not All Make the Recapitalisation Deadline. The Question Is Which.",
    deck: "Five names, the maths on each, and what an orderly resolution would look like.",
    author: "aluko",
    publishedISO: "2026-04-27",
    publishedDisplay: "27 Apr 2026",
    readMinutes: 12,
    rebuttedBy: [{ slug: "y", author: "Anonymous, Tier-2 Bank CFO", title: "On Risk-Weighted Assets and the Recapitalisation Maths", date: "29 Apr 2026" }],
  },
  {
    slug: "minimum-wage-real-erosion",
    topic: "labour",
    kicker: "Labour",
    headline: "The ₦70,000 Minimum Wage, in Real Terms, Is Already Below the 2019 Floor",
    deck: "The agreement was signed eleven months ago. CPI has done the rest.",
    author: "bello",
    publishedISO: "2026-04-24",
    publishedDisplay: "24 Apr 2026",
    readMinutes: 7,
    rebuttedBy: [],
  },
  {
    slug: "states-debt-overhang",
    topic: "subnation",
    kicker: "Subnational fiscal",
    headline: "Six States Are Insolvent on Any Reasonable Definition. The FAAC Cushion Is Disappearing.",
    deck: "The 2025 federation account boom is unwinding. The states that spent it are now exposed.",
    author: "okoro",
    publishedISO: "2026-04-20",
    publishedDisplay: "20 Apr 2026",
    readMinutes: 10,
    rebuttedBy: [],
  },
];

// Synthesis post — weaves multiple pieces into a thread.
const SYNTHESIS = {
  slug: "fiscal-monetary-misalignment-may-2026",
  kicker: "Synthesis · Issue 18",
  headline: "Fiscal-Monetary Misalignment: Where The Numbers Don't Add Up",
  deck: "Five pieces published over the last fortnight describe a single problem from five angles. Read together, they suggest the 2026 budget framework rests on revenue and inflation assumptions that the markets have already stopped believing.",
  editor: "Adesuwa Iyamah, on behalf of the editors",
  publishedDisplay: "12 May 2026",
  readMinutes: 18,
  threads: [
    { num: "I",   title: "The fiscal anchor is gone",
      summary: "Subnational FAAC dependence has reasserted itself; six states are insolvent on a reasonable definition.",
      pieces: ["states-debt-overhang", "subsidy-three-years-on"] },
    { num: "II",  title: "The monetary stance is tighter than it looks",
      summary: "The NAFEM window's effective liquidity is thinner than disclosed turnover suggests, which strengthens — not weakens — the case for a June hike.",
      pieces: ["phantom-liquidity-fx-window"] },
    { num: "III", title: "Inflation is regionally divergent in a way the headline number obscures",
      summary: "Northern food inflation has run 4–6 points hot for eleven months. The minimum wage is already below its 2019 floor in real terms.",
      pieces: ["northern-inflation-divergence", "minimum-wage-real-erosion"] },
    { num: "IV",  title: "Banking-sector capacity to absorb the shock is overstated",
      summary: "Five Tier-2 banks will miss the recapitalisation deadline absent a Tier-1 acquisition.",
      pieces: ["tier-2-banks-recapitalisation"] },
    { num: "V",   title: "What an honest 2026 budget revision would look like",
      summary: "We invited a fiscal economist to outline the revisions implied by the four threads above.",
      pieces: [] },
  ],
};

const REBUTTAL_THREADS = [
  {
    original: "phantom-liquidity-fx-window",
    originalTitle: "The Phantom Liquidity in Nigeria's FX Window",
    originalAuthor: "Adesuwa Iyamah",
    originalDate: "08 May 2026",
    responses: [
      { author: "Dr. Ngozi Okeke",      affiliation: "FMDQ Exchange",        title: "Reading the NAFEM Tape Correctly",          date: "11 May 2026", stance: "rebuts" },
      { author: "CBN Research Dept.",   affiliation: "Central Bank of Nigeria", title: "A Note on Aggregated Turnover Disclosures", date: "10 May 2026", stance: "rebuts" },
      { author: "Adesuwa Iyamah",       affiliation: "Author",               title: "On The CBN's Note — A Reply",                date: "12 May 2026", stance: "extends" },
    ],
  },
  {
    original: "subsidy-three-years-on",
    originalTitle: "Three Years After Removal, The Subsidy Is Back.",
    originalAuthor: "Chuka Okoro",
    originalDate: "06 May 2026",
    responses: [
      { author: "NNPCL Office of the GCEO", affiliation: "NNPCL",            title: "On Cost-Recovery Pricing",                    date: "07 May 2026", stance: "rebuts" },
    ],
  },
  {
    original: "tier-2-banks-recapitalisation",
    originalTitle: "The Tier-2 Banks Will Not All Make the Recapitalisation Deadline.",
    originalAuthor: "Tunde Aluko",
    originalDate: "27 Apr 2026",
    responses: [
      { author: "Anonymous, Tier-2 CFO",   affiliation: "Tier-2 commercial bank, name withheld", title: "On Risk-Weighted Assets and the Recapitalisation Maths", date: "29 Apr 2026", stance: "rebuts" },
      { author: "Tunde Aluko",             affiliation: "Author",            title: "On the CFO's Reply: What the Numbers Still Say", date: "30 Apr 2026", stance: "extends" },
    ],
  },
  {
    original: "afcfta-customs-quiet-failure",
    originalTitle: "AfCFTA's Quiet Failure at the Customs Counter",
    originalAuthor: "Chuka Okoro",
    originalDate: "29 Apr 2026",
    responses: [
      { author: "Ekene Mba",               affiliation: "Nigeria Customs Service", title: "The Forms Are Necessary — A Reply",          date: "02 May 2026", stance: "rebuts" },
    ],
  },
];

Object.assign(window, { AUTHORS, TOPICS, ARTICLES, ARTICLE_FX_PHANTOM, SYNTHESIS, REBUTTAL_THREADS });
